name: Docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: 'Create env file'
        run: |
<<<<<<< HEAD
          echo "${{ toJSON(secrets) }}" > .env
=======
          echo "${{ secrets.ENV_FILE }}" > .env
>>>>>>> b38ab62a8696d5f2c605af9516cc12e4313b5949
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: auto-trading/main-server:latest